name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  ci:
    name: Check Format, Lint, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check Format (Prettier)
        run: bun run pretty:check

      - name: Run Linter
        run: bun run lint

      - name: Run Tests
        run: bun run test

      - name: Build Project
        run: bun run build

  release-please:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.PAT }}
          config-file: release-please-config.json
