name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      
      - run: bun run build:all
        
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/ccsync-linux
            dist/ccsync-macos-x64
            dist/ccsync-macos-arm64
            dist/ccsync-windows.exe
          generate_release_notes: true