name: Run Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        runtime: [bun]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        if: matrix.runtime == 'bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies (Bun)
        if: matrix.runtime == 'bun'
        run: bun install

      - name: Run Tests (Bun)
        if: matrix.runtime == 'bun'
        run: bun run test
