name: Version Check

on:
  pull_request:
    branches:
      - master
    paths:
      - "package.json"
      - "src/version.ts"

permissions:
  contents: read

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Check version consistency
        id: version-check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Extract version from package.json
          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "Package.json version: $PKG_VERSION"

          # Extract version directly from TypeScript file using Bun
          TS_VERSION=$(bun --silent -e "import { version } from './src/version'; console.log(version)")
          echo "version.ts version: $TS_VERSION"

          # Compare versions
          if [ "$PKG_VERSION" != "$TS_VERSION" ]; then
            echo "::error::Version mismatch! package.json ($PKG_VERSION) does not match version.ts ($TS_VERSION)"
            exit 1
          else
            echo "Versions match: $PKG_VERSION"
          fi

          # Also check if this is a version bump PR from release-please
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" == "chore(master): release "* ]]; then
            echo "This appears to be a release-please PR, skipping tag check"
            exit 0
          fi

          # Get latest tag using GitHub API
          echo "Getting latest tag..."
          if ! LATEST_TAG=$(gh api repos/${{ github.repository }}/tags --jq '.[0].name // "0.0.0"'); then
            echo "Failed to get tags from GitHub API, using 0.0.0 as default"
            LATEST_TAG="0.0.0"
          else
            echo "Latest git tag: $LATEST_TAG"
          fi

          # Strip 'v' prefix if present in tag
          LATEST_TAG=${LATEST_TAG#v}

          # Compare package version with latest tag
          if [ "$PKG_VERSION" != "$LATEST_TAG" ] && [ "$PKG_VERSION" != "0.0.0" ]; then
            echo "::warning::Package version ($PKG_VERSION) does not match latest git tag ($LATEST_TAG). This is expected for version bump PRs."
          fi
